import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { z } from 'https://deno.land/x/zod@v3.22.4/mod.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');

// Input validation schemas
const PropertyDataSchema = z.object({
  title: z.string().min(1).max(200).trim(),
  description: z.string().min(1).max(2000).trim(),
  price: z.string().min(1).max(100).trim(),
  address: z.string().min(1).max(300).trim()
});

const RequestSchema = z.object({
  platform: z.enum(['facebook', 'instagram']),
  propertyData: PropertyDataSchema
});

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    
    // Validate input
    const validationResult = RequestSchema.safeParse(body);
    if (!validationResult.success) {
      return new Response(
        JSON.stringify({ 
          error: 'Invalid input data',
          details: validationResult.error.issues
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    
    const { platform, propertyData } = validationResult.data;

    if (!GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY not configured');
    }

    // Platform-specific prompts
    const prompts = {
      facebook: `Crea una descripción CORTA (máximo 150 palabras) de esta propiedad para Facebook. Incluye:
- 2-3 características principales
- Precio y ubicación
- Call-to-action breve
- 3-4 hashtags (#InmobiliariaKW #Propiedad #[Ciudad])
- Tono profesional

Propiedad: ${propertyData.title}
Descripción: ${propertyData.description}
Precio: ${propertyData.price}
Dirección: ${propertyData.address}`,

      instagram: `Genera un caption CORTO para Instagram (máximo 120 palabras). Incluye:
- Descripción visual y atractiva (60 palabras máx)
- 5-6 hashtags relevantes (#InmobiliariaKW #[TipoPropiedad] #[Ciudad])
- 2-3 emojis apropiados
- Tono inspiracional

Propiedad: ${propertyData.title}
Descripción: ${propertyData.description}
Precio: ${propertyData.price}
Dirección: ${propertyData.address}`
    };

    const prompt = prompts[platform as keyof typeof prompts];
    if (!prompt) {
      throw new Error('Platform not supported');
    }

    // Call Gemini API
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          topK: 1,
          topP: 1,
          maxOutputTokens: 2048,
        },
        safetySettings: [
          {
            category: "HARM_CATEGORY_HARASSMENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_HATE_SPEECH",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_DANGEROUS_CONTENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          }
        ]
      }),
    });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('Gemini API error:', response.status, errorText);
        // Return generic error message to client
        throw new Error('Failed to generate content');
      }

    const data = await response.json();
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!generatedText) {
      throw new Error('No content generated by Gemini');
    }

    console.log(`Generated ${platform} content:`, generatedText);

    return new Response(JSON.stringify({ 
      generatedContent: generatedText,
      platform 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in generate-social-content function:', error);
    return new Response(JSON.stringify({ 
      error: error instanceof Error ? error.message : 'Unknown error'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});