import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";
import { corsHeaders } from "../_shared/cors.ts";

const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const lovableApiKey = Deno.env.get('LOVABLE_API_KEY')!;

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { propertyId } = await req.json();
    console.log('Generating social images for property:', propertyId);

    const supabase = createClient(supabaseUrl, supabaseKey);

    // Fetch property data
    const { data: property, error: propertyError } = await supabase
      .from('properties')
      .select('*')
      .eq('id', propertyId)
      .single();

    if (propertyError || !property) {
      throw new Error(`Property not found: ${propertyError?.message}`);
    }

    // Fetch profile data
    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('*')
      .eq('user_id', property.user_id)
      .single();

    if (profileError) {
      console.warn('Profile not found:', profileError.message);
    }

    // Generate images using Lovable AI (Gemini)
    const generateImageWithAI = async (platform: string, width: number, height: number) => {
      const aspectRatio = width / height;
      const aspectRatioText = aspectRatio === 1 ? "1:1 cuadrado" : 
                              aspectRatio > 1.5 ? "horizontal (1.91:1)" : "vertical (9:16)";

      const prompt = `Crear una imagen profesional de publicación inmobiliaria para ${platform} en formato ${aspectRatioText}, aspecto ratio ${width}x${height}px.

CONTENIDO A INCLUIR:
- Título grande en la parte superior con fondo rojo: "¡NUEVA PROPIEDAD!"
- Precio destacado: ${property.price || 'Consultar precio'}
- Dirección: ${property.address || 'Ubicación privilegiada'}
- Texto: "Recién Listado"

DISEÑO VISUAL:
${platform === 'Instagram Feed (1080x1080)' ? `
- Layout cuadrado dividido en secciones
- Imagen principal de la propiedad ocupando 60% del espacio
- Dos imágenes pequeñas en el lateral derecho
- Sección inferior con información del agente: ${profile?.full_name || 'Agente Inmobiliario'}
- Iconos de teléfono y email con datos de contacto
` : platform === 'Instagram Stories (1080x1920)' ? `
- Layout vertical aprovechando toda la altura
- Imagen principal de propiedad en la parte superior (60%)
- Información de precio y ubicación en el medio
- Dos imágenes medianas debajo
- Información del agente en la parte inferior
` : `
- Layout horizontal optimizado para Facebook
- Imagen principal a la izquierda (70%)
- Información clave a la derecha: precio, ubicación
- Barra inferior con datos del agente
`}

ESTILO:
- Moderno y profesional
- Colores: rojo (#dc2626) para header, blanco y grises claros para el fondo
- Tipografía limpia y legible
- Incluir iconos de teléfono y email junto a la información de contacto
- QR code placeholder en esquina inferior derecha

CALIDAD:
- Alta resolución
- Aspecto profesional de agencia inmobiliaria
- Limpio y organizado
- Fácil de leer en dispositivos móviles`;

      console.log(`Generating ${platform} image with prompt...`);
      
      const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${lovableApiKey}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "google/gemini-2.5-flash-image-preview",
          messages: [
            {
              role: "user",
              content: prompt
            }
          ],
          modalities: ["image", "text"]
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`AI API error: ${response.status} ${errorText}`);
      }

      const data = await response.json();
      const generatedImageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;

      if (!generatedImageUrl) {
        throw new Error('No image generated by AI');
      }

      console.log(`${platform} image generated successfully`);
      return generatedImageUrl;
    };

    // Upload base64 image to Supabase Storage
    const uploadImage = async (base64Data: string, fileName: string) => {
      // Remove data:image/png;base64, prefix if present
      const base64Content = base64Data.replace(/^data:image\/\w+;base64,/, '');
      
      // Convert base64 to Uint8Array
      const binaryString = atob(base64Content);
      const bytes = new Uint8Array(binaryString.length);
      for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
      }

      const { data: uploadData, error: uploadError } = await supabase.storage
        .from('property-images')
        .upload(`${propertyId}/${fileName}`, bytes, {
          contentType: 'image/png',
          upsert: true,
        });

      if (uploadError) {
        throw uploadError;
      }

      const { data: { publicUrl } } = supabase.storage
        .from('property-images')
        .getPublicUrl(`${propertyId}/${fileName}`);

      return publicUrl;
    };

    // Generate all three images
    const sizes = [
      { name: 'instagram', width: 1080, height: 1080, platform: 'Instagram Feed (1080x1080)' },
      { name: 'stories', width: 1080, height: 1920, platform: 'Instagram Stories (1080x1920)' },
      { name: 'facebook', width: 1200, height: 630, platform: 'Facebook (1200x630)' },
    ];

    const results: Record<string, string> = {};

    for (const size of sizes) {
      console.log(`Generating ${size.name} image...`);
      
      const base64Image = await generateImageWithAI(size.platform, size.width, size.height);
      
      const fileName = `${size.name}-${Date.now()}.png`;
      const publicUrl = await uploadImage(base64Image, fileName);
      results[`${size.name}Url`] = publicUrl;
      
      console.log(`${size.name} image uploaded:`, publicUrl);
    }

    // Update property with image URLs
    const { error: updateError } = await supabase
      .from('properties')
      .update({
        generated_image_instagram: results.instagramUrl,
        generated_image_stories: results.storiesUrl,
        generated_image_facebook: results.facebookUrl,
      })
      .eq('id', propertyId);

    if (updateError) {
      throw updateError;
    }

    console.log('All images generated successfully:', results);

    return new Response(
      JSON.stringify({ 
        success: true, 
        images: results 
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );

  } catch (error) {
    console.error('Error generating social images:', error);
    return new Response(
      JSON.stringify({ 
        success: false, 
        error: error.message 
      }),
      { 
        status: 500, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  }
});
