// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtkphubycpmygsvhtuvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0a3BodWJ5Y3BteWdzdmh0dXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTAzMzcsImV4cCI6MjA2Nzk4NjMzN30.F3tinNWn5RoJI3m9BvA8vuS1_0NEyKvY68ZPJamqd6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});